steps:

- name: 'mcr.microsoft.com/dotnet/core/sdk:3.1'
  entrypoint: 'dotnet'
  args: [ 'publish', '-c', 'Release' ]
  dir: 'GcpPoc/GcpWebApi'

- name: 'gcr.io/cloud-builders/gcloud'
  args: ['app','deploy','GcpPoc/GcpWebApi/bin/Release/netcoreapp3.1/publish/app.yaml', '--verbosity=debug']
  timeout: '1200s'