steps:

  # Install node packages
  - name: 'gcr.io/cloud-builders/npm:current'
    args: [ 'install' ]
    dir: 'gcp-ng-app'

  # Build productive files
  - name: 'gcr.io/cloud-builders/npm:current'
    args: [ 'run', 'build', '--prod' ]
    dir: 'gcp-ng-app'

  # Deploy to google cloud app egnine
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['app', 'deploy', '--version=prod']
    dir: 'gcp-ng-app'
