steps:

  - name: 'gcr.io/cloud-builders/npm:current'
    args: [ 'install' ]
    dir: 'gcp-ng-app'

  - name: 'gcr.io/cloud-builders/npm:current'
    args: [ 'run', 'build', '--prod' ]
    dir: 'gcp-ng-app'

  # Build app.yaml to \dist folder
  - name: 'gcr.io/cloud-builders/npm:current'
    args: [ 'run', 'copy-yaml' ]
    dir: 'gcp-ng-app'

  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['app', 'deploy', '--version=prod']
    dir: 'gcp-ng-app'
